return {
	title = "The Link",
	id= "TheLinkTagset",
	items = {
		{'com.adobe.label', label="The Link"},
		'lewis.TheLink.Metadata.*',
		'com.adobe.separator',
		{'com.adobe.label', label="Exif and Camera Data"},
		-- 'com.adobe.filename',
		-- -- 'com.adobe.copyname',
		-- 'com.adobe.folder',
		-- 'com.adobe.title',
		-- { 'com.adobe.caption', height_in_lines = 3 },
		-- 'com.adobe.dateCreated',
		"com.adobe.copyright",
		"com.adobe.rating",
		"com.adobe.captureDate",
		"com.adobe.imageFileDimensions",
		"com.adobe.lens",
		"com.adobe.approximateFocusDistance",
		"com.adobe.exposureAndISO",
		"com.adobe.lensSetting",
		"com.adobe.GPS",
		"com.adobe.dateTime.timeOnly",
		"com.adobe.captureDateTime",
		"com.adobe.filesize",
		"com.adobe.focalLength",
		"com.adobe.focalLength35mm",
		"com.adobe.flash",
		"com.adobe.combinedCameraName",
		"com.adobe.sidecars",
		"com.adobe.filename",
		"com.adobe.keywords",
		"com.adobe.shutterSpeedValue",
		"com.adobe.originalFilename",
	}
}